$l = [System.Collections.Generic.List[string]]::new()
$l.Add("* { margin: 0; padding: 0; box-sizing: border-box; -webkit-tap-highlight-color: transparent; }")
$l.Add("html { overflow-x: hidden; width: 100%; }")
$l.Add("body { font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif; background-color: #f5f5f5; color: #000; overflow-x: hidden; width: 100%; margin: 0; padding: 0; -webkit-overflow-scrolling: touch; }")
$l.Add(".app { max-width: 100%; width: 100%; margin: 0 auto; background-color: #f5f5f5; min-height: 100vh; padding-bottom: 80px; overflow-x: hidden; position: relative; }")
$l.Add(".header { background: linear-gradient(135deg, #FFE600 0%, #FFF200 100%); padding: 12px 16px 0; margin: 0; width: 100%; }")
$l.Add(".header-content { display: flex; justify-content: space-between; align-items: center; padding-bottom: 16px; }")
$l.Add(".user-info { display: flex; align-items: center; gap: 10px; }")
$l.Add(".logo-mp { height: 28px; width: auto; }")
$l.Add(".greeting { font-size: 16px; font-weight: 600; color: #000; }")
$l.Add(".header-actions { display: flex; gap: 10px; }")
$l.Add(".icon-btn { width: 36px; height: 36px; border-radius: 50%; background-color: rgba(255,255,255,0.5); border: none; display: flex; align-items: center; justify-content: center; cursor: pointer; position: relative; }")
$l.Add(".notification .badge { position: absolute; top: 3px; right: 3px; background-color: #ff3b3b; color: white; font-size: 9px; font-weight: 700; width: 16px; height: 16px; border-radius: 50%; display: flex; align-items: center; justify-content: center; }")
$l.Add(".tabs { background: linear-gradient(135deg, #FFE600 0%, #FFF200 100%); display: flex; gap: 3px; padding: 0 16px 0; overflow-x: auto; position: relative; margin: 0; width: 100%; }")
$l.Add(".tabs::-webkit-scrollbar { display: none; }")
$l.Add(".tab { padding: 12px 20px; border-radius: 20px 20px 0 0; border: none; background-color: transparent; font-size: 14px; font-weight: 500; color: rgba(0,0,0,0.6); cursor: pointer; white-space: nowrap; position: relative; z-index: 2; }")
$l.Add(".tab.active { background-color: #f5f5f5; color: #000; font-weight: 600; }")
$l.Add(".content { padding: 0; background-color: #f5f5f5; position: relative; z-index: 0; }")
$l.Add(".content::before { content: ''; position: absolute; top: 0; left: 0; right: 0; height: 100px; background: linear-gradient(135deg, #FFE600 0%, #FFF200 100%); border-radius: 0 0 32px 32px; z-index: 0; }")
$l.Add(".balance-card { background-color: white; padding: 20px 24px 24px; border-radius: 0 24px 20px 20px; margin: 0 20px 16px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); position: relative; z-index: 1; min-height: 100px; }")
$l.Add(".balance-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 4px; gap: 12px; width: 100%; }")
$l.Add(".balance-amount { display: flex; align-items: baseline; gap: 8px; cursor: pointer; flex: 1; min-width: 0; }")
$l.Add(".currency { font-size: 32px; font-weight: 600; color: #2D3748; line-height: 1; flex-shrink: 0; }")
$l.Add(".value { font-size: 56px; font-weight: 700; color: #2D3748; letter-spacing: -1px; line-height: 1; white-space: nowrap; }")
$l.Add(".eye-btn { background: none; border: none; cursor: pointer; padding: 0; display: flex; align-items: center; margin-left: 4px; }")
$l.Add(".eye-btn svg { width: 40px; height: 40px; }")
$l.Add(".extract-link { color: #5B5FD8; text-decoration: none; font-size: 14px; font-weight: 600; margin-top: 4px; }")
$l.Add(".cdi-info { color: #00A650; font-size: 16px; font-weight: 600; margin-top: 8px; }")
$l.Add(".promo-card { background: #C6F6D5; padding: 20px; border-radius: 20px; margin-top: 20px; }")
$l.Add(".promo-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; }")
$l.Add(".promo-header h3 { font-size: 17px; font-weight: 600; color: #2D3748; line-height: 1.3; margin: 0; }")
$l.Add(".progress-bar { width: 100%; height: 4px; background-color: rgba(0,0,0,0.1); border-radius: 2px; margin-bottom: 14px; }")
$l.Add(".progress-fill { width: 30%; height: 100%; background-color: #00A650; border-radius: 2px; }")
$l.Add(".promo-bottom { display: flex; justify-content: space-between; align-items: flex-end; gap: 16px; }")
$l.Add(".promo-text { font-size: 14px; color: #4A5568; line-height: 1.4; font-weight: 400; flex: 1; margin: 0; }")
$l.Add(".promo-text .highlight { color: #00A650; font-weight: 600; }")
$l.Add(".btn-primary { background-color: #4361EE; color: white; border: none; padding: 12px 24px; border-radius: 10px; font-size: 15px; font-weight: 700; cursor: pointer; white-space: nowrap; flex-shrink: 0; align-self: flex-end; }")
$l.Add(".credit-section { margin: 0 20px 24px; }")
$l.Add(".section-title { font-size: 18px; font-weight: 600; margin-bottom: 16px; display: flex; align-items: center; gap: 8px; }")
$l.Add(".visa-logo { font-size: 16px; font-weight: 700; color: #1A1F71; }")
$l.Add(".card-icon-img { height: 28px; width: auto; margin-left: 6px; vertical-align: middle; }")
$l.Add(".credit-card { border-radius: 20px; overflow: hidden; margin-bottom: 24px; }")
$l.Add(".card-bg-image { width: 100%; height: auto; display: block; }")
$l.Add(".loan-section { margin: 0 20px 16px; }")
$l.Add(".link-primary { color: #5B5FD8; text-decoration: none; font-size: 14px; font-weight: 600; }")
$l.Add(".credit-line-card { background-color: #fff; padding: 20px; border-radius: 16px; display: flex; justify-content: space-between; align-items: center; gap: 16px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); margin: 0 20px 20px; }")
$l.Add(".credit-line-card p { flex: 1; font-size: 14px; line-height: 1.4; color: #000; }")
$l.Add(".bottom-nav { position: fixed; bottom: 0; left: 0; right: 0; max-width: 100%; width: 100%; background-color: #fff; display: flex; justify-content: space-around; align-items: center; padding: 12px 8px 16px; border-top: 1px solid #e0e0e0; box-shadow: 0 -2px 10px rgba(0,0,0,0.05); z-index: 9999; }")
$l.Add(".nav-item { display: flex; flex-direction: column; align-items: center; gap: 6px; background: none; border: none; color: #4A5568; cursor: pointer; font-size: 12px; font-weight: 500; padding: 4px 8px; flex: 1; position: relative; }")
$l.Add(".nav-item.active { color: #4361EE; }")
$l.Add(".nav-item.active::before { content: ''; position: absolute; top: -16px; left: 50%; transform: translateX(-50%); width: 60px; height: 3px; background-color: #4361EE; border-radius: 3px; }")
$l.Add(".nav-item.active svg { fill: #4361EE; }")
$l.Add(".nav-icon-img { width: 35px; height: 35px; object-fit: contain; }")
$l.Add(".nav-center { position: relative; margin-top: -32px; }")
$l.Add(".nav-circle { width: 64px; height: 64px; background: linear-gradient(135deg, #4DD4C0 0%, #32BCAD 100%); border-radius: 50%; display: flex; align-items: center; justify-content: center; margin-bottom: 4px; box-shadow: 0 4px 16px rgba(50,188,173,0.4); }")
$l.Add(".pix-icon { width: 38px; height: 38px; object-fit: contain; filter: brightness(0) saturate(100%) invert(100%); }")
[System.IO.File]::WriteAllLines("$PSScriptRoot\mp.css", $l)
Write-Host "ok"
